/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type CoreUserTransformer from '#app/core/transformers/user_transformer'

export namespace Data {
  export namespace Core {
    export type User = InferData<CoreUserTransformer>
    export namespace User {
      export type Variants = InferVariants<CoreUserTransformer>
    }
  }
}
